version: 2

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: dockerhub

jobs:
  build:
    docker:
      - image: marcosx/docker-builder:0.0.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Lint Dockerfile
          command: hadolint Dockerfile
      - run:
          name: Build local image (local/docker-builder)
          command: |
            docker build . -t local/docker-builder
      - run:
          name: Scan the local image with trivy
          command: trivy --clear-cache --no-progress --severity HIGH,CRITICAL local/docker-builder
      - run:
          name: Local tests
          command: |
            inspec exec test \
              -t docker://$(docker run -it --rm -d local/docker-builder sh)
      - run:
          name: DevSec Tests
          command: |
            inspec exec --no-distinct-exit linux-baseline-2.3.0 cis-docker-benchmark-2.1.0 \
              -t docker://$(docker run -it --rm -d local/docker-builder sh)
      - publish

commands:
  publish:
    parameters:
      tag:
        type: string
        default: $CIRCLE_SHA1
        description: Docker tag
    steps:
      - run:
          name: Publish dev version
          command: |
            docker tag local/docker-builder marcosx/docker-builder:<< parameters.tag >>
            docker login -u "${DOCKER_LOGIN}" -p "${DOCKER_PASSWORD}"
            docker push marcosx/docker-builder:$CIRCLE_SHA1
